[project]
name = "dotbins"
version = "0.1.0"
description = "Keep updated binaries in your dotfiles"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyyaml>=6.0.2",
    "requests",
]

[dependency-groups]
dev = [
    "python-magic>=0.4.27",
]
